_target_: dare2d.model.tap2d.Tap2D

defaults:
  - losses: tap2d_losses.yaml
  - optimizer: adam.yaml
  - losses@metrics: tap2d_losses.yaml
  - metrics@evaluations: null # tap2d_losses.yaml

target_size: ${crop_size}
